# Используем официальный образ PostgreSQL
FROM postgres:16-alpine

# Устанавливаем переменные окружения для инициализации базы
ENV POSTGRES_USER=Egrik
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=pg


